# Site
name: Pratik Rathod
description: Personal Blog
meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.png"
paginate: 10
baseurl:
google_analytics: "UA-54596203-1"
disqus: ""
mailchimp-list: ""

# Authors
authors:
  pratik:
    name: Pratik
    display_name: Pratik
    gravatar: 0bf0f1e25f1f45e09f0bd3a193cf2392
    email: pratik.rathod@gmail.com
    web: https://www.pratikrathod.com
    twitter: https://twitter.com/pratik_rathod
    description: "Learner. Adventurer. Entrepreneur. VP Product at @aboutPolar"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Other
markdown: kramdown
highlighter: rouge

title: Pratik Rathod
show_downloads: true
theme: jekyll-theme-cayman
